### ISSUE TITLE
PhpStorm plugin

### ISSUE THREAD

**Issue by ivandoric** [daftspunk/october-twig#2]
Hey @daftspunk is there going to be simillar plugin for PhpStorm?

Thanks.

**Comment by daftspunk** [comment]
I haven't used PhpStorm before.  This Sublime plugin doesn't seem to work quite how I want it, either. 
 The syntax package for October simply must be a combination of **PHP, Twig and HTML** parsers against the `.htm` file extension.  Using PHP alone will often bring HTML as well, so it is good enough. 
 The extra nice part would be somehow adding Twig to the mix.  If anyone has success in this area, please share your results.
