### ISSUE TITLE
Loading error after Sublime update

### ISSUE THREAD

**Issue by kombimedia** [daftspunk/october-twig#4]
Hey Sam,

Just updated Sublime and have lost syntax highlighting. Getting the below error. Any thoughts?

Error loading syntax file "Packages/October Twig Highlighter/october-twig.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit

Cheers

**Comment by daftspunk** [comment]
Hey @kombimedia I could never get this to work properly, it is a simple requirement:

PHP code + Twig code layers on top

The closest I've seen someone get is this package: 

https://github.com/dqsully/octobercms-template-language

But this is for VSCode unfortunately

**Comment by kombimedia** [comment]
Thanks for coming back so fast @daftspunk . Stink. I've removed the package, so I at least I have some syntax highlighting back.

Cheers

**Comment by Alex-BSD** [comment]
I confirm that this is happening to me too. It's a really helpful package for me, I hope it'll be fixed.

**Comment by daftspunk** [comment]
Fixed by #7
