### ISSUE TITLE
VS Code Syntax Highlights, but I don't have Autocompletion

### ISSUE THREAD

**Issue by artistro08** [daftspunk/october-twig#6]
In VS Code, if I install the extension, I'll get syntax Highlights, but I don't have any code completion. Emmet doesn't work either.

**Comment by daftspunk** [comment]
Hey @artistro08! For emmet could you try adding this config:

```
"emmet.includeLanguages": {
    "october-htm": "html"
},
```

Still working on code completion. I hope this helps.

**Comment by artistro08** [comment]
Looks like that didn't work, but looking forward to code completion!

**Comment by daftspunk** [comment]
Interesting. I tested this emmet config and it works for me.

**Comment by artistro08** [comment]
Works for me now too. Probably a user error
