### ISSUE TITLE
Commenting not working?

### ISSUE THREAD

**Issue by chrisvidal** [daftspunk/october-twig#8]
Commenting not working on twig code lines. Is there a way to implement it?

**Comment by daftspunk** [comment]
Not sure what you mean. If this is a bug: what action do you perform and what is the expectation vs actual result?

**Comment by chrisvidal** [comment]
sorry I was not clear;
the keyboard shortcut `command + /` does not comment the highlighted code line like it does for HTML, PHP, etc....

**Comment by daftspunk** [comment]
Hey @chrisvidal 

October Code → https://marketplace.visualstudio.com/items?itemName=SergeyKasyanov.october-code ← has replaced this package, so we will mark this one as read-only.
