### ISSUE TITLE
Doesn't work with PhpStorm 2022.1.3

### ISSUE THREAD

**Issue by olivierneo** [daftspunk/october-twig#9]
Hello, this bundle is not working on Build #PS-221.5921.28, built on June 22, 2022. I don't know if it worked on oldest versions.
There is no error message.

**Comment by daftspunk** [comment]
I'm sorry we don't use PhpStorm and have no ability to test this. We would happily accept a pull request to rectify any issues regarding this. 

Using the latest version of October, you can use any Twig package and assign them to `.htm` files. The backend views now use a different file extension, and this makes `.htm` a dedicated extension for theme files.
